image: INTERNAL_REGISTRY_TLD/NAMESPACE/rhel7-docker-ansibleci:latest

stages:
  - syntax
  - review
  - integration

ansible-syntax-check: 
  stage: syntax
  script:
  - find . -maxdepth 1 -name "*yml" ! -name ".*.yml" | xargs ansible-playbook --syntax-check

ansible-lint:
  stage: review
  script:
  - find . -name "*.yml" ! -name ".*.yml" | grep -v vault_ | xargs ansible-lint

ansible-review:
  stage: review
  script: 
  - find . -name "*.yml" -o -name "*.j2" ! -name ".*.yml"  | grep -v vault_ | xargs ansible-review -c .ansible-review/config.ini

test-kitchen:
  stage: integration
  script:
  - bundle 
  - bundle exec kitchen test general-rhel --destroy=always
