---
driver:
  name: docker

driver_config:
  socket: <%= ENV['DOCKER_HOST'] %>
  use_cache: true
  privileged: true
  use_sudo: false
  hostname: dockertest.tld
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  provision_command:
    - yum install -y hostname

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: localhost
  ansible_verbose: true
  ansible_verbosity: 4
  require_chef_for_busser: false

verifier:
  name: inspec

platforms:
  - name: rhel
    driver_plugin: docker
    driver_config:
      image: rhel7/rhel
      run_command: /sbin/init

#test suite. is there a better way? ie - roles/*/*/*/*rb
suites:
  - name: default
    verifier:
      patterns:
      - roles/telnet/integration/serverspec/telnet.rb
