image: icts/rhel7-ansible-ci:latest

stages:
  - syntax
  - review
  - integration

ansible-syntax-check: 
  stage: syntax
  script:
  - find . -maxdepth 1 -name "*yml" ! -name "*root*" ! -name .kitchen.yml ! -name .gitlab-ci.yml |xargs ansible-playbook --syntax-check 

ansible-review:
  stage: review
  script: 
  - find . -name "*yml" ! -path "*root*" ! -name .kitchen.yml ! -name .gitlab-ci.yml |xargs ansible-review

test-kitchen:
  stage: integration
  script:
  - bundle 
  - bundle exec kitchen test general-rhel --destroy=always
